### ISSUE TITLE
Password parameter needs to be encoded

### ISSUE THREAD

**Issue by hakimaryan** [meritec/progresso_client#1]
Password parameter needs to be encoded, as it says in documentation
https://progresso.docs.apiary.io/#reference/authorisation/request-token

**Comment by mikecmpbll** [comment]
docs for reference https://progresso.docs.apiary.io/#reference/authorisation/access-tokens/request-token

**Comment by mikecmpbll** [comment]
presumably this was fixed in https://github.com/meritec/progresso_client/commit/4776f88900d576f530ba47f272684e7b92c0e415 ? closing.

**Comment by hakimaryan** [comment]
potential encoding issue still, reopening.
